# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vendedores.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(974, 666)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(130, 70, 161, 41))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(0, 0, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(35, 159, 151);")
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(130, 140, 671, 441))
        self.frame_3.setStyleSheet("background-color: rgb(35, 159, 151);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.tableWidget = QtWidgets.QTableWidget(self.frame_3)
        self.tableWidget.setGeometry(QtCore.QRect(20, 20, 631, 401))
        self.tableWidget.setStyleSheet("background-color: rgb(200, 200, 200);")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setGeometry(QtCore.QRect(830, 140, 131, 161))
        self.frame_4.setStyleSheet("background-color: rgb(35, 159, 151);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.Create_Buttom = QtWidgets.QPushButton(self.frame_4)
        self.Create_Buttom.setGeometry(QtCore.QRect(10, 10, 111, 41))
        self.Create_Buttom.setStyleSheet("QPushButton {\n"
"    font: 75 8pt \"MS Shell Dlg 2\";\n"
"    border-radius: 15px; /* Ajusta el radio según tu preferencia */\n"
"    background-color: black;\n"
"    color: white;\n"
"    padding: 10px 20px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: gray;\n"
"}\n"
"\n"
"QPushButton {\n"
"    font-family: Arial;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    box-shadow: 0px 2px 5px rgba(0, 0, 0, 0.3);\n"
"}")
        self.Create_Buttom.setObjectName("Create_Buttom")
        self.Edit_Buttom = QtWidgets.QPushButton(self.frame_4)
        self.Edit_Buttom.setGeometry(QtCore.QRect(10, 60, 111, 41))
        self.Edit_Buttom.setStyleSheet("QPushButton {\n"
"    font: 75 8pt \"MS Shell Dlg 2\";\n"
"    border-radius: 15px; /* Ajusta el radio según tu preferencia */\n"
"    background-color: black;\n"
"    color: white;\n"
"    padding: 10px 20px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: gray;\n"
"}\n"
"\n"
"QPushButton {\n"
"    font-family: Arial;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    box-shadow: 0px 2px 5px rgba(0, 0, 0, 0.3);\n"
"}")
        self.Edit_Buttom.setObjectName("Edit_Buttom")
        self.Eliminate_Buttom = QtWidgets.QPushButton(self.frame_4)
        self.Eliminate_Buttom.setGeometry(QtCore.QRect(10, 110, 111, 41))
        self.Eliminate_Buttom.setStyleSheet("QPushButton {\n"
"    font: 75 8pt \"MS Shell Dlg 2\";\n"
"    border-radius: 15px; /* Ajusta el radio según tu preferencia */\n"
"    background-color: black;\n"
"    color: white;\n"
"    padding: 10px 20px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: gray;\n"
"}\n"
"\n"
"QPushButton {\n"
"    font-family: Arial;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    box-shadow: 0px 2px 5px rgba(0, 0, 0, 0.3);\n"
"}")
        self.Eliminate_Buttom.setObjectName("Eliminate_Buttom")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(-10, -10, 991, 681))
        self.label_2.setAcceptDrops(False)
        self.label_2.setAutoFillBackground(False)
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("Proyecto-de-Sistemas/Imagenes/img-6.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setWordWrap(False)
        self.label_2.setObjectName("label_2")
        self.label_2.raise_()
        self.frame_3.raise_()
        self.frame_4.raise_()
        self.frame_2.raise_()
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "VENDEDORES"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Nombres"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Apellidos"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Telofono"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Direccion"))
        self.Create_Buttom.setText(_translate("Form", "Crear"))
        self.Edit_Buttom.setText(_translate("Form", "Editar"))
        self.Eliminate_Buttom.setText(_translate("Form", "Eliminar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
