# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\juana\Desktop\Proyecto-de-Sistemas-main\vistas\vistas_disenos\vista_compra.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class CompraWindow(object):
    def setupUi(self, compras):
        compras.setObjectName("compras")
        compras.resize(798, 600)
        self.centralwidget = QtWidgets.QWidget(compras)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(340, 50, 131, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(200, 50, 121, 41))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(500, 50, 171, 41))
        self.pushButton_4.setObjectName("pushButton_4")
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(70, 200, 641, 331))
        self.tableView.setObjectName("tableView")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(70, 50, 121, 41))
        self.pushButton.setObjectName("pushButton")
        compras.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(compras)
        self.statusbar.setObjectName("statusbar")
        compras.setStatusBar(self.statusbar)

        self.retranslateUi(compras)
        QtCore.QMetaObject.connectSlotsByName(compras)

    def retranslateUi(self, compras):
        _translate = QtCore.QCoreApplication.translate
        compras.setWindowTitle(_translate("compras", "MainWindow"))
        self.pushButton_2.setText(_translate("compras", "Modificar Compra"))
        self.pushButton_3.setText(_translate("compras", "Eliminar Compra"))
        self.pushButton_4.setText(_translate("compras", "Libro de compra"))
        self.pushButton.setText(_translate("compras", "Añadir Compra"))
