# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'inventario_tintometrico.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(641, 380)
        self.tableView = QtWidgets.QTableView(Form)
        self.tableView.setGeometry(QtCore.QRect(20, 10, 471, 281))
        self.tableView.setObjectName("tableView")
        self.boton_agregar = QtWidgets.QPushButton(Form)
        self.boton_agregar.setGeometry(QtCore.QRect(510, 50, 93, 28))
        self.boton_agregar.setObjectName("boton_agregar")
        self.boton_editar = QtWidgets.QPushButton(Form)
        self.boton_editar.setGeometry(QtCore.QRect(510, 90, 93, 28))
        self.boton_editar.setObjectName("boton_editar")
        self.boton_eliminar = QtWidgets.QPushButton(Form)
        self.boton_eliminar.setGeometry(QtCore.QRect(510, 130, 93, 28))
        self.boton_eliminar.setObjectName("boton_eliminar")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 300, 55, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(130, 300, 55, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(240, 300, 55, 16))
        self.label_3.setObjectName("label_3")
        self.lineEdit_codigo = QtWidgets.QLineEdit(Form)
        self.lineEdit_codigo.setGeometry(QtCore.QRect(20, 320, 101, 22))
        self.lineEdit_codigo.setObjectName("lineEdit_codigo")
        self.lineEdit_color = QtWidgets.QLineEdit(Form)
        self.lineEdit_color.setGeometry(QtCore.QRect(130, 320, 101, 22))
        self.lineEdit_color.setObjectName("lineEdit_color")
        self.lineEdit_volumen = QtWidgets.QLineEdit(Form)
        self.lineEdit_volumen.setGeometry(QtCore.QRect(240, 320, 101, 22))
        self.lineEdit_volumen.setObjectName("lineEdit_volumen")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(510, 200, 91, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_precio = QtWidgets.QLineEdit(Form)
        self.lineEdit_precio.setGeometry(QtCore.QRect(350, 320, 113, 22))
        self.lineEdit_precio.setObjectName("lineEdit_precio")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(350, 300, 81, 16))
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.boton_agregar.setText(_translate("Form", "Agregar"))
        self.boton_editar.setText(_translate("Form", "Editar"))
        self.boton_eliminar.setText(_translate("Form", "Eliminar"))
        self.label.setText(_translate("Form", "Codigo"))
        self.label_2.setText(_translate("Form", "Color"))
        self.label_3.setText(_translate("Form", "Volumen"))
        self.label_4.setText(_translate("Form", "Precio por cc"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
