# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\enman\OneDrive\Escritorio\sistema de programas\Proyecto-de-Sistemas\vistas\login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(471, 406)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 471, 401))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("c:\\Users\\enman\\OneDrive\\Escritorio\\sistema de programas\\Proyecto-de-Sistemas\\vistas\\Imagenes/img-8.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(100, 90, 261, 191))
        self.widget.setStyleSheet("border-color: rgb(0, 0, 0);")
        self.widget.setObjectName("widget")
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setGeometry(QtCore.QRect(50, 0, 191, 20))
        self.label_7.setStyleSheet("font: 87 12pt \"Arial Black\";")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setGeometry(QtCore.QRect(60, 40, 131, 16))
        self.label_8.setStyleSheet("font: 87 9pt \"Arial Black\";")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setGeometry(QtCore.QRect(50, 90, 131, 16))
        self.label_9.setStyleSheet("font: 87 9pt \"Arial Black\";")
        self.label_9.setObjectName("label_9")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_3.setGeometry(QtCore.QRect(50, 60, 191, 20))
        self.lineEdit_3.setStyleSheet("border: 2px solid black;")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_4.setGeometry(QtCore.QRect(50, 110, 191, 20))
        self.lineEdit_4.setStyleSheet("border: 2px solid black;")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setGeometry(QtCore.QRect(100, 150, 75, 23))
        self.pushButton_2.setStyleSheet("font: 8pt \"Arial Black\";\n"
"color: #000;\n"
"font-weight: bold;\n"
"text-align: center;\n"
"border: 1px solid #000;\n"
"border-radius: 5px;\n"
"background-color: #f0f0f0;")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_10 = QtWidgets.QLabel(self.widget)
        self.label_10.setGeometry(QtCore.QRect(10, 100, 31, 31))
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("c:\\Users\\enman\\OneDrive\\Escritorio\\sistema de programas\\Proyecto-de-Sistemas\\vistas\\Imagenes/747305.png"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.widget)
        self.label_11.setGeometry(QtCore.QRect(0, 50, 51, 41))
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("c:\\Users\\enman\\OneDrive\\Escritorio\\sistema de programas\\Proyecto-de-Sistemas\\vistas\\Imagenes/6522581.png"))
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_7.setText(_translate("MainWindow", "Inicio De Sesión"))
        self.label_8.setText(_translate("MainWindow", "Usuario"))
        self.label_9.setText(_translate("MainWindow", "Contraseña"))
        self.pushButton_2.setText(_translate("MainWindow", "Ingresar"))
