# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menudeinicio2.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(572, 360)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_superior = QtWidgets.QFrame(self.centralwidget)
        self.frame_superior.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_superior.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_superior.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.frame_superior.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_superior.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_superior.setObjectName("frame_superior")
        self.btn_Cerrar = QtWidgets.QPushButton(self.frame_superior)
        self.btn_Cerrar.setGeometry(QtCore.QRect(540, 10, 31, 31))
        self.btn_Cerrar.setStyleSheet("QPushButton{\n"
"border:0px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border:5px solid #aa00ff;\n"
"background-color:#00ff00;\n"
"}")
        self.btn_Cerrar.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Downloads/cerrar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_Cerrar.setIcon(icon)
        self.btn_Cerrar.setIconSize(QtCore.QSize(34, 34))
        self.btn_Cerrar.setObjectName("btn_Cerrar")
        self.btn_restaurar_2 = QtWidgets.QPushButton(self.frame_superior)
        self.btn_restaurar_2.setGeometry(QtCore.QRect(490, 10, 41, 31))
        self.btn_restaurar_2.setStyleSheet("QPushButton{\n"
"border:0px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border:5px solid #aa00ff;\n"
"background-color:#0000ff;\n"
"}")
        self.btn_restaurar_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../Downloads/maximizar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_restaurar_2.setIcon(icon1)
        self.btn_restaurar_2.setIconSize(QtCore.QSize(34, 34))
        self.btn_restaurar_2.setObjectName("btn_restaurar_2")
        self.btn_restaurar = QtWidgets.QPushButton(self.frame_superior)
        self.btn_restaurar.setGeometry(QtCore.QRect(440, 10, 41, 31))
        self.btn_restaurar.setStyleSheet("QPushButton{\n"
"border:0px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border:5px solid #aa00ff;\n"
"background-color:#ff0000;\n"
"}")
        self.btn_restaurar.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../Downloads/restaurar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_restaurar.setIcon(icon2)
        self.btn_restaurar.setIconSize(QtCore.QSize(34, 34))
        self.btn_restaurar.setObjectName("btn_restaurar")
        self.btn_minimizar = QtWidgets.QPushButton(self.frame_superior)
        self.btn_minimizar.setGeometry(QtCore.QRect(400, 10, 31, 31))
        self.btn_minimizar.setStyleSheet("QPushButton{\n"
"border:0px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border:5px solid #aa00ff;\n"
"background-color:#ffff00;\n"
"}")
        self.btn_minimizar.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../../Downloads/minimizar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_minimizar.setIcon(icon3)
        self.btn_minimizar.setIconSize(QtCore.QSize(34, 34))
        self.btn_minimizar.setObjectName("btn_minimizar")
        self.btn_menu = QtWidgets.QPushButton(self.frame_superior)
        self.btn_menu.setGeometry(QtCore.QRect(10, 10, 200, 35))
        self.btn_menu.setMinimumSize(QtCore.QSize(200, 35))
        self.btn_menu.setMaximumSize(QtCore.QSize(16777215, 35))
        self.btn_menu.setStyleSheet("QPushButton {\n"
"    background-color: #aa00f;\n"
"    font: 600 12pt \"Arial Black\";\n"
"    border-radius: 5px;\n"
"    box-shadow: 0px 2px 4px rgba(0, 0, 0, 0.2);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"    cursor: pointer;\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../../Downloads/barra-de-menus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_menu.setIcon(icon4)
        self.btn_menu.setObjectName("btn_menu")
        self.verticalLayout.addWidget(self.frame_superior)
        self.frame_inferior = QtWidgets.QFrame(self.centralwidget)
        self.frame_inferior.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_inferior.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_inferior.setObjectName("frame_inferior")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_inferior)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_ = QtWidgets.QFrame(self.frame_inferior)
        self.frame_.setMaximumSize(QtCore.QSize(200, 16777215))
        self.frame_.setStyleSheet("QFrame {\n"
"    background-color: rgb(0, 255, 255);\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: rgb(0, 255, 255);\n"
"    border-top-left-radius: 20px;\n"
"    border-bottom-left-radius: 20px;\n"
"\n"
"    font: 75 12pt \"Arial Narrow\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"    border-top-left-radius: 20px;\n"
"    border-bottom-left-radius: 20px;\n"
"\n"
"    font: 75 12pt \"Arial Narrow\";\n"
"}")
        self.frame_.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_.setObjectName("frame_")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_)
        self.pushButton_6.setGeometry(QtCore.QRect(14, 20, 121, 40))
        self.pushButton_6.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_6.setMaximumSize(QtCore.QSize(16777215, 40))
        self.pushButton_6.setStyleSheet("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../../Downloads/comprar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon5)
        self.pushButton_6.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_6.setObjectName("pushButton_6")
        self.label = QtWidgets.QLabel(self.frame_)
        self.label.setGeometry(QtCore.QRect(30, 190, 141, 20))
        self.label.setStyleSheet("font: 16pt \"Arial Narrow\";")
        self.label.setObjectName("label")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_)
        self.pushButton_7.setGeometry(QtCore.QRect(14, 60, 121, 40))
        self.pushButton_7.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_7.setMaximumSize(QtCore.QSize(16777215, 40))
        self.pushButton_7.setStyleSheet("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../../Downloads/ventasicono.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_7.setIcon(icon6)
        self.pushButton_7.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_)
        self.pushButton_8.setGeometry(QtCore.QRect(24, 100, 111, 40))
        self.pushButton_8.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_8.setMaximumSize(QtCore.QSize(16777215, 40))
        self.pushButton_8.setStyleSheet("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("../../Downloads/inventario-green.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_8.setIcon(icon7)
        self.pushButton_8.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_)
        self.pushButton_9.setGeometry(QtCore.QRect(24, 140, 111, 40))
        self.pushButton_9.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_9.setMaximumSize(QtCore.QSize(16777215, 40))
        self.pushButton_9.setStyleSheet("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("../../Downloads/6522581.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_9.setIcon(icon8)
        self.pushButton_9.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_9.setObjectName("pushButton_9")
        self.label_3 = QtWidgets.QLabel(self.frame_)
        self.label_3.setGeometry(QtCore.QRect(40, 220, 101, 81))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("../../Downloads/inteligencia-artificial.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.frame_)
        self.frame_contenedor = QtWidgets.QFrame(self.frame_inferior)
        self.frame_contenedor.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_contenedor.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_contenedor.setObjectName("frame_contenedor")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_contenedor)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget = QtWidgets.QWidget(self.frame_contenedor)
        self.widget.setObjectName("widget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.widget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 371, 311))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_principal = QtWidgets.QWidget()
        self.page_principal.setObjectName("page_principal")
        self.pushButton = QtWidgets.QPushButton(self.page_principal)
        self.pushButton.setGeometry(QtCore.QRect(140, 100, 75, 23))
        self.pushButton.setStyleSheet("background-color: rgb(170, 0, 0);")
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(self.page_principal)
        self.label_2.setGeometry(QtCore.QRect(-24, -8, 401, 331))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../../Pictures/img-6.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.stackedWidget.addWidget(self.page_principal)
        self.page_uno = QtWidgets.QWidget()
        self.page_uno.setObjectName("page_uno")
        self.pushButton_2 = QtWidgets.QPushButton(self.page_uno)
        self.pushButton_2.setGeometry(QtCore.QRect(140, 110, 75, 23))
        self.pushButton_2.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.stackedWidget.addWidget(self.page_uno)
        self.page_dos = QtWidgets.QWidget()
        self.page_dos.setObjectName("page_dos")
        self.pushButton_3 = QtWidgets.QPushButton(self.page_dos)
        self.pushButton_3.setGeometry(QtCore.QRect(160, 130, 75, 23))
        self.pushButton_3.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.stackedWidget.addWidget(self.page_dos)
        self.page_tres = QtWidgets.QWidget()
        self.page_tres.setObjectName("page_tres")
        self.pushButton_4 = QtWidgets.QPushButton(self.page_tres)
        self.pushButton_4.setGeometry(QtCore.QRect(150, 120, 75, 23))
        self.pushButton_4.setStyleSheet("background-color: rgb(170, 0, 255);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.stackedWidget.addWidget(self.page_tres)
        self.page_cuatro = QtWidgets.QWidget()
        self.page_cuatro.setObjectName("page_cuatro")
        self.pushButton_5 = QtWidgets.QPushButton(self.page_cuatro)
        self.pushButton_5.setGeometry(QtCore.QRect(160, 120, 75, 23))
        self.pushButton_5.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.stackedWidget.addWidget(self.page_cuatro)
        self.verticalLayout_2.addWidget(self.widget)
        self.horizontalLayout.addWidget(self.frame_contenedor)
        self.verticalLayout.addWidget(self.frame_inferior)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_menu.setText(_translate("MainWindow", "    MENU"))
        self.pushButton_6.setText(_translate("MainWindow", "COMPRAS"))
        self.label.setText(_translate("MainWindow", "PINTA CONTROL"))
        self.pushButton_7.setText(_translate("MainWindow", "VENTAS"))
        self.pushButton_8.setText(_translate("MainWindow", "INVENTARIO"))
        self.pushButton_9.setText(_translate("MainWindow", "USUARIOS"))
        self.pushButton.setText(_translate("MainWindow", "1"))
        self.pushButton_2.setText(_translate("MainWindow", "2"))
        self.pushButton_3.setText(_translate("MainWindow", "3"))
        self.pushButton_4.setText(_translate("MainWindow", "4"))
        self.pushButton_5.setText(_translate("MainWindow", "5"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
