# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'USERS3.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1106, 796)
        self.Create_Buttom = QtWidgets.QPushButton(Form)
        self.Create_Buttom.setGeometry(QtCore.QRect(870, 200, 151, 41))
        self.Create_Buttom.setStyleSheet("QPushButton {\n"
"    font: 75 8pt \"MS Shell Dlg 2\";\n"
"    border-radius: 15px; /* Ajusta el radio según tu preferencia */\n"
"    background-color: black;\n"
"    color: white;\n"
"    padding: 10px 20px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: gray;\n"
"}\n"
"\n"
"QPushButton {\n"
"    font-family: Arial;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    box-shadow: 0px 2px 5px rgba(0, 0, 0, 0.3);\n"
"}")
        self.Create_Buttom.setObjectName("Create_Buttom")
        self.Edit_Buttom = QtWidgets.QPushButton(Form)
        self.Edit_Buttom.setGeometry(QtCore.QRect(870, 260, 151, 41))
        self.Edit_Buttom.setStyleSheet("QPushButton {\n"
"    font: 75 8pt \"MS Shell Dlg 2\";\n"
"    border-radius: 15px; /* Ajusta el radio según tu preferencia */\n"
"    background-color: black;\n"
"    color: white;\n"
"    padding: 10px 20px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: gray;\n"
"}\n"
"\n"
"QPushButton {\n"
"    font-family: Arial;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    box-shadow: 0px 2px 5px rgba(0, 0, 0, 0.3);\n"
"}")
        self.Edit_Buttom.setObjectName("Edit_Buttom")
        self.Eliminate_Buttom = QtWidgets.QPushButton(Form)
        self.Eliminate_Buttom.setGeometry(QtCore.QRect(870, 320, 151, 41))
        self.Eliminate_Buttom.setStyleSheet("QPushButton {\n"
"    font: 75 8pt \"MS Shell Dlg 2\";\n"
"    border-radius: 15px; /* Ajusta el radio según tu preferencia */\n"
"    background-color: black;\n"
"    color: white;\n"
"    padding: 10px 20px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: gray;\n"
"}\n"
"\n"
"QPushButton {\n"
"    font-family: Arial;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    box-shadow: 0px 2px 5px rgba(0, 0, 0, 0.3);\n"
"}")
        self.Eliminate_Buttom.setObjectName("Eliminate_Buttom")
        self.textEdit_ID = QtWidgets.QLineEdit(Form)
        self.textEdit_ID.setGeometry(QtCore.QRect(190, 610, 113, 22))
        self.textEdit_ID.setObjectName("textEdit_ID")
        self.textEdit_Nombres = QtWidgets.QLineEdit(Form)
        self.textEdit_Nombres.setGeometry(QtCore.QRect(320, 610, 113, 22))
        self.textEdit_Nombres.setObjectName("textEdit_Nombres")
        self.textEdit_Apellidos = QtWidgets.QLineEdit(Form)
        self.textEdit_Apellidos.setGeometry(QtCore.QRect(450, 610, 113, 22))
        self.textEdit_Apellidos.setObjectName("textEdit_Apellidos")
        self.textEdit_email = QtWidgets.QLineEdit(Form)
        self.textEdit_email.setGeometry(QtCore.QRect(580, 610, 113, 22))
        self.textEdit_email.setObjectName("textEdit_email")
        self.textEdit_Telefono = QtWidgets.QLineEdit(Form)
        self.textEdit_Telefono.setGeometry(QtCore.QRect(710, 610, 113, 22))
        self.textEdit_Telefono.setObjectName("textEdit_Telefono")
        self.textEdit_Buscar = QtWidgets.QLineEdit(Form)
        self.textEdit_Buscar.setGeometry(QtCore.QRect(880, 430, 113, 22))
        self.textEdit_Buscar.setObjectName("textEdit_Buscar")
        self.tableView = QtWidgets.QTableView(Form)
        self.tableView.setGeometry(QtCore.QRect(190, 150, 631, 401))
        self.tableView.setObjectName("tableView")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(190, 580, 55, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(320, 580, 55, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(450, 580, 71, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(580, 580, 55, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(710, 580, 55, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(880, 400, 101, 16))
        self.label_6.setObjectName("label_6")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Create_Buttom.setText(_translate("Form", "Crear"))
        self.Edit_Buttom.setText(_translate("Form", "Editar"))
        self.Eliminate_Buttom.setText(_translate("Form", "Eliminar"))
        self.label.setText(_translate("Form", "ID"))
        self.label_2.setText(_translate("Form", "Nombre"))
        self.label_3.setText(_translate("Form", "Contraseña"))
        self.label_4.setText(_translate("Form", "e-mail"))
        self.label_5.setText(_translate("Form", "Telefono"))
        self.label_6.setText(_translate("Form", "Buscar Usuario"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
